- hosts: rocky9
  strategy: debug
  become: true
  roles:
#    - role: davidkarban.openssh
#      tags:
#        - "ssh"
#    - role: geerlingguy.postgresql
#      tags:
#        - "postgre"
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.java
    - role: robertdebock.tomcat
  tasks:
    - fail:

- hosts: serverd
  become: true
  roles:
    - role: ansibleguy.infra_nginx
    - role: ansibleguy.infra_docker_minimal
    - role: ansibleguy.sw_awx
