- hosts: rocky9
  become: true
  roles:
#    - role: davidkarban.openssh
#      tags:
#        - "ssh"
#    - role: geerlingguy.postgresql
#      tags:
#        - "postgre"
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.java
    - role: robertdebock.tomcat

- hosts: ansible_machine
  become: true
  roles:
    - geerlingguy.docker
    - role: crazikpl.awx_deploy
