- hosts: all
  become: true
  # Velikost davky, pocet serveru co pobezi paralelne najednou
  serial:
    - 1
    - 5
    - 10
  # Kolik procent max muze padnout, aby se jeste pokracovalo.
  max_fail_percentage: 20%
  vars:
    rhel_updates_excludes:
      - "xfsprogs"
  tasks:
    - name: Update all packages
      dnf:
       # best: true/false
        name: "*"
        exclude: "{{ rhel_updates_excludes | default(omit) }}"
        state: latest
        update_cache: true
      register: result

    - name: Reboot
      ansible.builtin.reboot:
        msg: "Automatic reboot after updates."

    - debug:
        var: result.results
      when: result.changed

    - debug:
        msg: "No packages were updated."
      when: not result.changed|default(false)
